# apiVersion: v1
# kind: Pod
# metadata:
#   name: secret-env-pod
# spec:
#   containers:
#   - name: mycontainer
#     image: redis
#     env:
#       - name: SECRET_USERNAME
#         valueFrom:
#           secretKeyRef:
#             name: mysecret
#             key: username
#       - name: SECRET_PASSWORD
#         valueFrom:
#           secretKeyRef:
#             name: mysecret
#             key: password
#   restartPolicy: Never

# spec:
#   replicas: 2
#   strategy:
#   type: RollingUpdate
#   rollingUpdate:
#     maxSurge: 1
#     maxUnavailable: 25%

apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: redis
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: mysecret